services:
  process:
    class: DependencyInjectionTraining\Process
    arguments:
      - @email-notifier
      - @storage

  email-notifier:
    class: DependencyInjectionTraining\EmailNotifier
   
  storage:
    class: DependencyInjectionTraining\Storage\Storage
    
    class: DependencyInjectionTraining\Storage\Storage
    arguments:
      - @pdoconfig
      
  pdoconfig:
    class: DependencyInjectionTraining\PdoConfig